# Generated by Django 3.0.3 on 2020-03-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('size', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='size')),
                ('path', models.CharField(max_length=200, verbose_name='path')),
            ],
        ),
    ]
