# Generated by Django 3.0.3 on 2020-03-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='size'),
        ),
    ]
