# Generated by Django 3.0.3 on 2020-03-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200319_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='timestamp',
            field=models.DecimalField(decimal_places=5, default=12.1, max_digits=20, verbose_name='timestamp'),
            preserve_default=False,
        ),
    ]
