# Generated by Django 3.0.3 on 2020-03-20 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_file_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.CharField(max_length=50, verbose_name='timestamp'),
        ),
    ]
